apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admin-api.fullname" . }}
  labels:
    app: {{ include "admin-api.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "admin-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "admin-api.name" . }}
    spec:
      serviceAccountName: scansure-admin-sa
      containers:
        - name: admin-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: KRATOS_PUBLIC_URL
              value: {{ .Values.env.KRATOS_PUBLIC_URL }}
            - name: KETO_ADMIN_TOKEN_FILE
              value: {{ .Values.env.KETO_ADMIN_TOKEN_FILE }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets
              readOnly: true
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.secretProviderClass }}
