apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: scansure-vault-spc
  namespace: scansure
spec:
  provider: vault
  parameters:
    vaultAddress: "https://vault.scansure"
    roleName: "scansure-role"
    objects: |
      - objectName: "kratos_admin_token"
        secretPath: "secret/data/scansure/kratos/admin"
        objectType: "secret"
      - objectName: "keto_admin_token"
        secretPath: "secret/data/scansure/keto/admin"
        objectType: "secret"
