# 1️⃣ Welcome endpoint — open for sanity testing
- id: welcome
  match:
    url: "<^https?://(localhost|127\\.0\\.0\\.1)(:4455)?/welcome$>"
    methods: ["GET"]
  upstream:
    url: "https://httpbin.org/status/200"
    strip_path: "/welcome"
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop

# 2️⃣ Kratos public self-service endpoints (browser sessions)
- id: kratos-public
  match:
    url: "<^https?://(localhost|127\\.0\\.0\\.1)(:4455)?/self-service/.*$>"
    methods: ["GET","POST"]
  upstream:
    url: "http://kratos:4433"
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: noop

# 3️⃣ Kratos Admin API (/identities etc.) — JWT required
- id: kratos-admin
  match:
    url: "<^https?://(localhost|127\\.0\\.0\\.1)(:4455)?/admin(/.*)?$>"
    methods: ["GET","POST","PUT","DELETE"]
  upstream:
    url: "http://kratos:4434"
    strip_path: ""
  authenticators:
    - handler: jwt
      config:
        jwks_urls:
          - file:///etc/config/jwks/.well-known/jwks.json
        trusted_issuers:
          - local-dev
        target_audience:
          - oathkeeper
        #required_scope:
        #  - admin
  authorizer:
    handler: allow
  mutators:
    - handler: noop


- id: kratos-public-login
  match:
    url: "<^https?://(localhost|127\\.0\\.0\\.1)(:4455)?/self-service/login/browser$>"
    methods: ["GET", "POST"]
  upstream:
    url: "http://kratos:4433"
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: noop

